// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerCredentials = {
  ip_address: string;
  port: string;
  username: string;
  password: string;
};
